---
- name: selinux to permissive
  shell: setenforce Permissive

- name: move proxy.sh
  shell: mv /etc/profile.d/proxy.sh /home/ec2-user
  
- name: Add date and time stamp 
  shell: echo "export PROMPT_COMMAND='echo -n \[\$(date +%F-%T)\]\ '" >> /etc/bashrc && echo "export HISTTIMEFORMAT='%F-%T '" >> /etc/bashrc && source /etc/bashrc

- name: Create sysadmin user account
  user:
    name: sysadmin
    update_password: always
    password: $6$0W4Wndec.lYN/B0m$f/XQZSGwyvMfgdj/eN1re8JzQd1./X/LoUMEdLJMb19ivNEYpuvG5ogygHZu6A6iH0F5oUONiNtd/1WFCUjEJ.
    shell: /bin/bash
    groups: wheel
    create_home: yes
  ignore_errors: true

- name: Update ssh to allow sysadmin ssh
  shell: |
    cp /etc/ssh/sshd_config /etc/ssh/sshd_config.ORIG
    sed -i -e 's|PasswordAuthentication no|PasswordAuthentication yes|g' /etc/ssh/sshd_config
    systemctl reload sshd

- name: unchattr resolv.conf
  shell: chattr -i /etc/resolv.conf 

- name: update dns
  shell: nmcli con mod 'System eth0' ipv4.dns "8.8.8.8 10.100.0.2"

- name: Reload NetworkManager
  shell: systemctl restart NetworkManager 

- name: Copy dnf.conf to client
  copy: src=dnf.conf  dest=/etc/dnf mode=0644

- name: Copy redhat-rhui.repo to client
  copy: src=redhat-rhui.repo  dest=/etc/yum.repos.d mode=0600

- name: Copy redhat-rhui-client-config.repo to client
  copy: src=redhat-rhui-client-config.repo  dest=/etc/yum.repos.d mode=0600

- name: dnf clean
  shell: dnf clean all

- name: install packages
  package:
    name: "{{ item }}"
    state: latest
  with_items:
  - vim
  - git

- name: Copy amazon-ssm-agent.gpg to client
  copy: src=amazon-ssm-agent.gpg  dest=/etc/pki/rpm-gpg mode=0644

- name: Install AWS SSM
  shell: |
    rpm --import /etc/pki/rpm-gpg/amazon-ssm-agent.gpg
    dnf install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm 
    systemctl enable amazon-ssm-agent 
    systemctl start amazon-ssm-agent

- name: Install EPEL and htop
  shell: |
    rpm --import https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
    dnf install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    dnf install htop -y

- name: Reinstall AIDE
  shell: | 
    cp /etc/aide.conf /etc/aide.conf.ORIG 
    cd /var/lib/aide/ && rm -rf *
    dnf remove aide -y
    dnf install aide -y 

- name: Copy scripts directory
  copy: src=scripts/  dest=/root/scripts/ mode=0600

- name: Set authselect
  shell: authselect select sssd --force

- name: Run run_scripts.sh
  shell: |
    chmod +x /root/scripts/run_scripts.sh
    chmod +x /root/scripts/bash_remediate_scripts/*
    /root/scripts/run_scripts.sh 

- name: selinux to enforcing
  shell: setenforce Enforcing 

- name: chattr resolv.conf
  shell: chattr +i /etc/resolv.conf 

